/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphik;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import mastermind.Mastermind;

/**
 *
 * @author Jordan
 */
public class ParametersUI extends javax.swing.JDialog implements ActionListener {

    public Integer maxTrials;
    public Integer gridWidth;
    public Integer logLevel;    
    public boolean isCanceled = false;
    public Integer gameMode;
    
    /**
     * Creates new form ParametersUI
     */
    public ParametersUI() {
        initComponents();
        
        exitButton.addActionListener(this);
        playOrdiVsOrdi.addActionListener(this);
        playOrdiVsUser.addActionListener(this);
        playUserVsOrdi.addActionListener(this);
        playUserVsUser.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logLevelRadioGroup = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gridWidthSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        maxTrialsSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        logLevel2 = new javax.swing.JRadioButton();
        logLevel1 = new javax.swing.JRadioButton();
        logLevel0 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        playOrdiVsOrdi = new javax.swing.JButton();
        playUserVsOrdi = new javax.swing.JButton();
        playOrdiVsUser = new javax.swing.JButton();
        playUserVsUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paramètres");
        setBounds(new java.awt.Rectangle(20, 20, 200, 20));
        setMinimumSize(new java.awt.Dimension(430, 220));
        setPreferredSize(new java.awt.Dimension(470, 280));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuration du mastermind");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jLabel1);

        getContentPane().add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paramètres de la partie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(416, 1));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Largeur de la grille (nombre de pions à deviner)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        gridWidthSpinner.setMaximumSize(new java.awt.Dimension(40, 20));
        gridWidthSpinner.setMinimumSize(new java.awt.Dimension(40, 20));
        gridWidthSpinner.setPreferredSize(new java.awt.Dimension(40, 20));
        gridWidthSpinner.setValue(4);
        jPanel2.add(gridWidthSpinner, new java.awt.GridBagConstraints());

        jLabel3.setText("Nombre d'essais maximum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        maxTrialsSpinner.setMaximumSize(new java.awt.Dimension(40, 20));
        maxTrialsSpinner.setMinimumSize(new java.awt.Dimension(40, 20));
        maxTrialsSpinner.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(maxTrialsSpinner, gridBagConstraints);

        jLabel4.setText("Niveau de log");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel2.add(jLabel4, gridBagConstraints);

        logLevelRadioGroup.add(logLevel2);
        logLevel2.setText("Haut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        jPanel2.add(logLevel2, gridBagConstraints);

        logLevelRadioGroup.add(logLevel1);
        logLevel1.setText("Faible");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel2.add(logLevel1, gridBagConstraints);

        logLevelRadioGroup.add(logLevel0);
        logLevel0.setSelected(true);
        logLevel0.setText("Aucun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(logLevel0, gridBagConstraints);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commencer une partie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        playOrdiVsOrdi.setText("Ordi vs Ordi");
        jPanel1.add(playOrdiVsOrdi);

        playUserVsOrdi.setText("Vous vs Ordi");
        jPanel1.add(playUserVsOrdi);

        playOrdiVsUser.setText("Ordi vs Vous");
        playOrdiVsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playOrdiVsUserActionPerformed(evt);
            }
        });
        jPanel1.add(playOrdiVsUser);

        playUserVsUser.setText("Deux joueurs");
        jPanel1.add(playUserVsUser);

        getContentPane().add(jPanel1);

        exitButton.setText("Quitter");
        jPanel3.add(exitButton);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e){
        
        if(e.getSource() == playOrdiVsOrdi)
            gameMode = Mastermind.ORDI_VS_ORDI;
        else if(e.getSource() == playOrdiVsUser)
            gameMode = Mastermind.ORDI_VS_USER;
        else if(e.getSource() == playUserVsOrdi)
            gameMode = Mastermind.USER_VS_ORDI;
        else if(e.getSource() == playUserVsUser)
            gameMode = Mastermind.USER_VS_USER;
        else if(e.getSource() == exitButton)
            isCanceled = true;
                
        gridWidth = (Integer)gridWidthSpinner.getValue();
        maxTrials = (Integer)maxTrialsSpinner.getValue();
        
        if(logLevel0.isSelected())
            logLevel = 0;
        else if(logLevel1.isSelected())
            logLevel = 1;
        else 
            logLevel = 2;
        
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParametersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParametersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParametersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParametersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParametersUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JSpinner gridWidthSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton logLevel0;
    private javax.swing.JRadioButton logLevel1;
    private javax.swing.JRadioButton logLevel2;
    private javax.swing.ButtonGroup logLevelRadioGroup;
    private javax.swing.JSpinner maxTrialsSpinner;
    private javax.swing.JButton playOrdiVsOrdi;
    private javax.swing.JButton playOrdiVsUser;
    private javax.swing.JButton playUserVsOrdi;
    private javax.swing.JButton playUserVsUser;
    // End of variables declaration//GEN-END:variables
}
